version: "3.8"
services:

  mariadb:
    image: mariadb:10.6
    working_dir: /application
    volumes:
      - .:/application
    env_file: ./environment/mariadb.env
    ports:
      - "3306:3306"

  webserver:
    image: nginx:alpine
    working_dir: /application
    volumes:
      - .:/application
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    working_dir: /application
    env_file: ./environment/php-fpm.env
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    depends_on: 
      - webserver

  composer:
    build:
      context: .
      dockerfile: ./docker/composer/Dockerfile
    volumes:
      - ./src:/application

  adminer:
    image: adminer
    ports:
      - 8001:8080
    depends_on:
      - mariadb
